name: Build Image
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v4
      with:
        repository: 'guysoft/CustomPiOS'
        ref: devel
        fetch-depth: 0
        path: CustomPiOS

    - name: Pin CustomPiOS version
      run: |
        cd CustomPiOS
        git checkout ea6fa50

    - name: Checkout Project Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: repository

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 12.x

    - name: Build React frontend
      run: |
        pushd repository/naturewatch_camera_server/static/client
        npm i -y
        npm run build
        popd

    - name: Download Raspbian Image
      run: |
        cd repository/os/image
        wget -q -c 'https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-01-28/2022-01-28-raspios-bullseye-armhf-lite.zip'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/os
        ../../CustomPiOS/src/update-custompios-paths

    - name: Copy NaturewatchCameraServer to CustomPiOS directory
      run: |
        cp -r repository /tmp/NaturewatchCameraServer
        rm -rf /tmp/NaturewatchCameraServer/os
        rm -rf /tmp/NaturewatchCameraServer/naturewatch_camera_server/static/client/node_modules
        mv /tmp/NaturewatchCameraServer repository/os/modules/naturewatchcamera/filesystem/home/pi/NaturewatchCameraServer
        ls repository/os/modules/naturewatchcamera/filesystem/home/pi/NaturewatchCameraServer

    - name: Build Image
      run: |
        export BASE_IMAGE_ENLARGEROOT=2000
        export AUTO_HOTSPOT_NAME=MyNaturewatch
        export AUTO_HOTSPOT_PASSWORD=badgersandfoxes
        sudo modprobe loop && cd repository/os
        sudo bash -x ./build_dist

    - name: Copy Output
      run: cp ${{ github.workspace }}/repository/os/workspace/*lite.img mynaturewatch-camera.img

    - name: Zip Output
      run: gzip mynaturewatch-camera.img

    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mynaturewatch-camera.img.gz
        path: mynaturewatch-camera.img.gz

    - name: Create Draft Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        draft: true
        prerelease: false
        files: mynaturewatch-camera.img.gz
